# roles/xoa/defaults/main.yml
---
xoa_server_pkgs:
  - build-essential
  - libpng-dev
  - redis-server
  - libvhdi-utils
  - nfs-common
  - lvm2
  - cifs-utils

install_xo_cli: true
xo-cli_email:
xo-cli_password:
xo-cli_permission: admin
xo-cli_allow_unauthorized: true
xo-cli_url: http://127.0.0.1
