# roles/xoa/tasks/users.yml
---
- name: Register xo-cli with XO server (if credentials provided)
  shell: >-
    xo-cli register --allowUnauthorized {{ xo_cli_url }} {{ xo_cli_email }} {{ xo_cli_password }}
  become: true
  when:
  - xo_cli_email
  - xo_cli_password
  - xo_cli_allow_unauthorized

- name: Create operator user with xo-cli (if credentials provided)
  shell: >-
    xo-cli user.create email={{ xo_cli_email }} password={{ xo_cli_password }} permission={{ xo_cli_permission }}
  become: true
  when:
  - xo_cli_email
  - xo_cli_password
