#
# playbooks/k8s.yaml
# Manage Kubernetes cluster setup with kubeadm
#

- name: Install common k8s packages
  hosts: deployed_vms
  vars:
    ansible_user: vagrant

  roles:
    - role: roles/k8s-common


- name: Install K8s master packages
  hosts: k8s-master_vms
  vars:
    ansible_user: vagrant

  roles:
    - {role: roles/k8s-master}

- name: Query kubeadm join cmd string
  hosts: k8s-master_vms
  vars:
    ansible_user: vagrant

  tasks:

    - name: "DEBUG groups"
      debug:
        msg: "{{ groups }}"

    - name: "DEBUG group names"
      debug:
        msg: "{{ group_names }}"

    - name: Get token to join cluster
      command: "kubeadm token create --print-join-command"
      become: true
      register: kubeadm_token_raw

    - debug:
        msg: "{{ kubeadm_token_raw.stdout }}"

    - name: set join command
      set_fact:
        kubeadm_token: "{{ kubeadm_token_raw.stdout_lines[0] }}"

    - name: write join command to local
      local_action: shell echo "{{ kubeadm_token }} "> ../token.txt


- name: kubeadm join master
  hosts: k8s-worker_vms
  vars:
    ansible_user: vagrant
    kubeadm_token: "{{ lookup('file', '../token.txt') }}"

  tasks:
    - name: Use token to join cluster
      command: "{{ kubeadm_token }}"
      become: true
      register: kubeadm_join
      when: k8s_worker
