# roles/k8s-master/tasks/main.yml
---
- name: kubeadm init
  command: "kubeadm init --pod-network-cidr={{ flannel_pod_cidr }} --control-plane-endpoint={{ kube_api_endpoint}}"
  become: true

- name: Create filepath for root kubeconfig 
  file:
    path: "/root/.kube"
    state: directory
    mode: '0750'
    owner: root
  become: true

- name: Create filepath for operator kubeconfig 
  file:
    path: "/home/{{ operator_user }}/.kube"
    state: directory
    mode: '0750'
    owner: "{{ operator_user }}"
  become: true

- name: setup root kubeconfig
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/root/.kube/config"
    remote_src: true
    owner: "{{ operator_user }}"
  become: true

- name: setup operator kubeconfig
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ operator_user }}/.kube/config"
    remote_src: true
    owner: "{{ operator_user }}"
  become: true
  with_items:
    - "{{ operator_user }}"

- name: Create Flannel Network config from template
  template:
    src: kube-flannel.yml.j2
    dest: /root/kube-flannel.yml
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Apply Flannel Network config
  command: "kubectl apply -f /root/kube-flannel.yml"
  become: true
  register: flanell_result
  until: flanell_result.rc == 0
  retries: 10
  delay: 1

- name: Create Flannel RBAC config from template
  template:
    src: kube-flannel-rbac.yml.j2
    dest: /root/kube-flannel-rbac.yml
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Apply Flannel RBAC config
  command: "kubectl apply -f /root/kube-flannel-rbac.yml"
  become: true

- find: paths="/root" recurse=yes patterns="*.yml"
  register: root_files_to_delete
  become: true

- name: Cleanup yaml files
  file:
    path: "{{ item }}"
    state: absent
  become: true
  with_items:
    - "{{ root_files_to_delete.files }}"
