# roles/k8s-common/tasks/main.yml
---
- name: Ensure K8s required OS base pacakges are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_pkgs }}"
  become: true

- name: Create filepath for containerd config
  file:
    path: /etc/containerd
    state: directory
    mode: '0750'
    owner: root
  become: true

- name: Generate containerd static config
  command: |
    containerd config default > /etc/containerd/config.toml
  become: true
  register: containerd_config

- name: Creating a file with content
  copy:
    dest: "/etc/containerd/config.toml"
    content: "{{ containerd_config.stdout }}"
  become: true

- name: Fix containerd cgroup setting
  lineinfile:
    path: "/etc/containerd/config.toml"
    regex: "^(.*)SystemdCgroup(.*)"
    line: "            SystemdCgroup = true"
  become: true

- name: Config br_netfilter module
  lineinfile:
    path: /etc/modules
    line: "br_netfilter"
  become: true

- name: Runtime load br_netfilter module
  command: "modprobe br_netfilter"
  become: true

- name: Set sysctl.conf settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  with_dict: "{{ sysctl_conf }}"
  become: true

- name: Restart service containerd, in all cases
  service:
    name: containerd
    state: restarted
  become: true

- name: get k8s repo gpg key
  get_url:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    dest: "/usr/share/keyrings/kubernetes-archive-keyring.gpg"
  become: true

- name: add k8s apt repository
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: kubernetes.list
    update_cache: true
  become: true

- name: Install k8s binaries
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ k8s_pkgs }}"
  become: true

