# roles/k8s-common/tasks/main.yml
---
- name: Force-remove containerd if it is already installed
  package:
    name: "containerd"
    state: absent
  become: true

- name: Create filepath for containerd config
  file:
    path: /etc/containerd
    state: directory
    mode: '0750'
    owner: root
  become: true

- name: Check if /data path exists
  stat:
    path: "/data"
  register: data_path

- name: Remove existing /var/lib/containerd
  file:
    path: /var/lib/containerd
    state: absent
  become: true
  when: data_path and data_path.stat.isdir

- name: Create filepath for containerd data
  file:
    path: /data/var/lib/containerd
    state: directory
    mode: '0750'
    owner: root
  become: true
  when: data_path and data_path.stat.isdir

- name: Symlink /var/lib/containerd to /data/var/lib/containerd
  file:
    src: /data/var/lib/containerd
    dest: /var/lib/containerd
    owner: root
    group: root
    state: link
  become: true
  when: data_path and data_path.stat.isdir

- name: Ensure K8s required OS base pacakges are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_pkgs }}"
  become: true

- name: Generate containerd static config
  command: |
    containerd config default > /etc/containerd/config.toml
  become: true
  register: containerd_config

- name: Creating a file with content
  copy:
    dest: "/etc/containerd/config.toml"
    content: "{{ containerd_config.stdout }}"
  become: true

- name: Fix containerd cgroup setting
  lineinfile:
    path: "/etc/containerd/config.toml"
    regex: "^(.*)SystemdCgroup(.*)"
    line: "            SystemdCgroup = true"
  become: true

- name: Config br_netfilter module
  lineinfile:
    path: /etc/modules
    line: "br_netfilter"
  become: true

- name: Runtime load br_netfilter module
  command: "modprobe br_netfilter"
  become: true

- name: Set sysctl.conf settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  with_dict: "{{ sysctl_conf }}"
  become: true

- name: Create custom static /etc/resolvd-k8s.conf from template
  template:
    src: resolved.conf.j2
    dest: "{{ resolved_file_kubelet }}"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Restart service containerd, in all cases
  service:
    name: containerd
    state: restarted
  become: true

- name: get k8s repo gpg key
  get_url:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    dest: "/usr/share/keyrings/kubernetes-archive-keyring.gpg"
  become: true

- name: add k8s apt repository
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: kubernetes.list
    update_cache: true
  become: true

- name: Install k8s binaries
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ k8s_pkgs }}"
  become: true

- name: Create filepath for kubelet config
  file:
    path: /var/lib/kubelet
    state: directory
    mode: '0750'
    owner: root
  become: true


- name: Patch kubelet systemd config to use custom settings
  template:
    src: kubelet.service.d/10-kubeadm.conf
    dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    owner: root
    group: root
    mode: '640'
  become: true

- name: Patch kubelet config.yaml to use custom settings
  template:
    src: kubelet/config.yaml
    dest: "{{ kubelet_config_args }}"
    owner: root
    group: root
    mode: '640'
  become: true

- name: Restart service kubelet, in all cases
  service:
    name: kubelet
    state: restarted
  become: true
